# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: mcp.proto
# Protobuf Python Version: 5.29.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    29,
    0,
    '',
    'mcp.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\tmcp.proto\x12\x03mcp\"!\n\x0eMCPChatMessage\x12\x0f\n\x07message\x18\x01 \x01(\t\"]\n\x0fMCPChatResponse\x12\x12\n\nuser_query\x18\x01 \x01(\t\x12 \n\x18retrieved_context_chunks\x18\x02 \x03(\t\x12\x14\n\x0cllm_response\x18\x03 \x01(\t\"&\n\x11MCPProcessRequest\x12\x11\n\tdirectory\x18\x01 \x01(\t\"\x8a\x01\n\x12MCPProcessResponse\x12\x0f\n\x07message\x18\x01 \x01(\t\x12\x0e\n\x06status\x18\x02 \x01(\t\x12\x17\n\x0fprocessed_files\x18\x03 \x01(\x05\x12\x1a\n\x12total_chunks_added\x18\x04 \x01(\x05\x12\x1e\n\x16\x63ollection_total_items\x18\x05 \x01(\x05\x32\x84\x01\n\nMCPService\x12\x31\n\x04\x43hat\x12\x13.mcp.MCPChatMessage\x1a\x14.mcp.MCPChatResponse\x12\x43\n\x10ProcessDocuments\x12\x16.mcp.MCPProcessRequest\x1a\x17.mcp.MCPProcessResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'mcp_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_MCPCHATMESSAGE']._serialized_start=18
  _globals['_MCPCHATMESSAGE']._serialized_end=51
  _globals['_MCPCHATRESPONSE']._serialized_start=53
  _globals['_MCPCHATRESPONSE']._serialized_end=146
  _globals['_MCPPROCESSREQUEST']._serialized_start=148
  _globals['_MCPPROCESSREQUEST']._serialized_end=186
  _globals['_MCPPROCESSRESPONSE']._serialized_start=189
  _globals['_MCPPROCESSRESPONSE']._serialized_end=327
  _globals['_MCPSERVICE']._serialized_start=330
  _globals['_MCPSERVICE']._serialized_end=462
# @@protoc_insertion_point(module_scope)
