# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import mcp_pb2 as mcp__pb2

GRPC_GENERATED_VERSION = '1.71.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in mcp_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class MCPServiceStub(object):
    """Service definition for Model Context Protocol
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Chat = channel.unary_unary(
                '/mcp.MCPService/Chat',
                request_serializer=mcp__pb2.MCPChatMessage.SerializeToString,
                response_deserializer=mcp__pb2.MCPChatResponse.FromString,
                _registered_method=True)
        self.ProcessDocuments = channel.unary_unary(
                '/mcp.MCPService/ProcessDocuments',
                request_serializer=mcp__pb2.MCPProcessRequest.SerializeToString,
                response_deserializer=mcp__pb2.MCPProcessResponse.FromString,
                _registered_method=True)


class MCPServiceServicer(object):
    """Service definition for Model Context Protocol
    """

    def Chat(self, request, context):
        """RPC for chat functionality
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ProcessDocuments(self, request, context):
        """RPC for document processing functionality
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_MCPServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Chat': grpc.unary_unary_rpc_method_handler(
                    servicer.Chat,
                    request_deserializer=mcp__pb2.MCPChatMessage.FromString,
                    response_serializer=mcp__pb2.MCPChatResponse.SerializeToString,
            ),
            'ProcessDocuments': grpc.unary_unary_rpc_method_handler(
                    servicer.ProcessDocuments,
                    request_deserializer=mcp__pb2.MCPProcessRequest.FromString,
                    response_serializer=mcp__pb2.MCPProcessResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'mcp.MCPService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('mcp.MCPService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class MCPService(object):
    """Service definition for Model Context Protocol
    """

    @staticmethod
    def Chat(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/mcp.MCPService/Chat',
            mcp__pb2.MCPChatMessage.SerializeToString,
            mcp__pb2.MCPChatResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ProcessDocuments(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/mcp.MCPService/ProcessDocuments',
            mcp__pb2.MCPProcessRequest.SerializeToString,
            mcp__pb2.MCPProcessResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
